import { accommodationImages } from './accommodation-images';

export type AccommodationFeature =
  | 'seaView'
  | 'pool'
  | 'garden'
  | 'center'
  | 'terrace'
  | 'modern'
  | 'beach'
  | 'wifi'
  | 'parking'
  | 'aircon'
  | 'tv';

export type Accommodation = {
  id: number;
  slug: string;
  title: string;
  subtitle: string;
  location: string;
  image: string;
  images: string[];
  features: AccommodationFeature[];
  price: number;
  guests: number;
  bedrooms: number;
  bookingUrl: string;
};

const withImages = (
  slug: string,
  data: Omit<Accommodation, 'slug' | 'image' | 'images'>,
): Accommodation => {
  const images = accommodationImages[slug] ?? [];
  return {
    ...data,
    slug,
    image: images[0] ?? '',
    images,
  };
};

export const accommodations: Accommodation[] = [
  withImages('beach-apartment', {
    id: 7,
    title: 'Beach Apartment',
    subtitle: 'T1 renovado a poucos passos da praia',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'tv', 'center'],
    price: 90,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/31781/',
  }),
  withImages('villa-manuelina', {
    id: 36,
    title: 'Villa Manuelina',
    subtitle: 'Villa de luxo com piscina aquecida',
    location: 'Sesimbra',
    features: ['pool', 'garden', 'parking', 'wifi', 'tv', 'beach'],
    price: 350,
    guests: 10,
    bedrooms: 5,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/26301/',
  }),
  withImages('olive-tree-house', {
    id: 26,
    title: 'Olive Tree House',
    subtitle: 'Moradia com piscina privada e BBQ',
    location: 'Sesimbra (Castelo)',
    features: ['pool', 'garden', 'parking', 'wifi', 'tv', 'beach'],
    price: 290,
    guests: 7,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/26784/',
  }),
  withImages('refugio', {
    id: 14,
    title: 'Refúgio',
    subtitle: 'Terraço privado com vista mar',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'terrace', 'seaView'],
    price: 90,
    guests: 5,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/30282/',
  }),
  withImages('vila-das-conchas', {
    id: 18,
    title: 'Vila das Conchas',
    subtitle: 'Piscina com vista mar',
    location: 'Sesimbra',
    features: ['pool', 'seaView', 'beach', 'wifi', 'parking', 'tv'],
    price: 100,
    guests: 6,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/30185/',
  }),
  withImages('casa-da-alegria', {
    id: 33,
    title: 'Casa da Alegria',
    subtitle: 'Piscina privada, jardim e BBQ',
    location: 'Lagoa de Albufeira',
    features: ['pool', 'garden', 'beach', 'parking', 'wifi', 'tv'],
    price: 200,
    guests: 9,
    bedrooms: 4,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/28463/',
  }),
  withImages('casa-da-lagoa', {
    id: 13,
    title: 'Casa da Lagoa',
    subtitle: 'Bungalow na Lagoa de Albufeira',
    location: 'Lagoa de Albufeira',
    features: ['beach', 'garden', 'parking', 'wifi', 'tv'],
    price: 80,
    guests: 5,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/23842/',
  }),
  withImages('sesimbra-vista-azul', {
    id: 8,
    title: 'Sesimbra Vista Azul',
    subtitle: 'Piscina e vista mar',
    location: 'Sesimbra',
    features: ['pool', 'seaView', 'beach', 'wifi', 'tv'],
    price: 70,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/31331/',
  }),
  withImages('casa-da-falesia', {
    id: 6,
    title: 'Casa da Falésia',
    subtitle: 'T1 no 13º andar com vista para a baía e a Praia da Califórnia',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv', 'seaView'],
    price: 80,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/24520/',
  }),
  withImages('seriz-beach-house', {
    id: 27,
    title: 'Seriz Beach House',
    subtitle: 'Casa com piscina, jardim e BBQ',
    location: 'Sesimbra',
    features: ['pool', 'garden', 'beach', 'parking', 'wifi', 'tv'],
    price: 120,
    guests: 7,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/32857/',
  }),
  withImages('villa-terracos-do-castelo', {
    id: 34,
    title: 'Villa Terraços do Castelo',
    subtitle: 'Vista panorâmica para o mar e a serra',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv', 'seaView', 'terrace'],
    price: 140,
    guests: 10,
    bedrooms: 4,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/24185/',
  }),
  withImages('trevo-beach-house', {
    id: 29,
    title: 'Trevo Beach House',
    subtitle: 'Moradia com piscina privada',
    location: 'Sesimbra',
    features: ['pool', 'garden', 'beach', 'parking', 'wifi', 'tv'],
    price: 200,
    guests: 8,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/31326/',
  }),
  withImages('sesimbra-99', {
    id: 1,
    title: 'Sesimbra 99',
    subtitle: 'Apartamento com vista mar, 5 min a pé da praia',
    location: 'Sesimbra',
    features: ['beach', 'wifi'],
    price: 70,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/29798/',
  }),
  withImages('casa-do-dario', {
    id: 2,
    title: 'Casa do Dário',
    subtitle: 'Studio a 50m da Praia de Sesimbra',
    location: 'Sesimbra',
    features: ['beach', 'center', 'wifi', 'tv'],
    price: 50,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/25150/',
  }),
  withImages('casa-do-castelo', {
    id: 3,
    title: 'Casa do Castelo',
    subtitle: 'T2 com jardim, perto da praia',
    location: 'Sesimbra',
    features: ['beach', 'garden', 'parking', 'wifi', 'tv'],
    price: 70,
    guests: 4,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/33273/',
  }),
  withImages('casa-azul', {
    id: 4,
    title: 'Casa Azul',
    subtitle: 'A 2 minutos a pé da praia, no centro histórico',
    location: 'Sesimbra',
    features: ['beach', 'center', 'wifi', 'tv'],
    price: 70,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/29032/',
  }),
  withImages('cantinho-da-gingeira', {
    id: 5,
    title: 'Cantinho da Gingeira',
    subtitle: 'Casa a 5 min da praia com jardim e churrasqueira',
    location: 'Lagoa de Albufeira',
    features: ['garden', 'beach', 'parking', 'wifi', 'tv'],
    price: 40,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/29065/',
  }),
  withImages('casa-ferreira', {
    id: 9,
    title: 'Casa Ferreira',
    subtitle: 'Estúdio a 2 min da praia',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'tv', 'center'],
    price: 45,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/24186/',
  }),
  withImages('casa-atlas', {
    id: 10,
    title: 'Casa Atlas',
    subtitle: 'T1 a 2 min da Praia de Sesimbra',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv'],
    price: 70,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/28191/',
  }),
  withImages('estudio-do-abacateiro', {
    id: 11,
    title: 'Estúdio do Abacateiro',
    subtitle: 'Casinha a 5 min da praia com jardim e churrasqueira',
    location: 'Lagoa de Albufeira',
    features: ['garden', 'beach', 'parking', 'wifi', 'tv'],
    price: 40,
    guests: 5,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/29074/',
  }),
  withImages('casa-luminosa', {
    id: 12,
    title: 'Casa Luminosa',
    subtitle: '160m da praia, no centro histórico de Sesimbra',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'center', 'terrace'],
    price: 80,
    guests: 5,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/28276/',
  }),
  withImages('mar-a-vista', {
    id: 15,
    title: 'Mar à Vista',
    subtitle: 'A 10 min a pé da praia, com vista mar',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv', 'seaView', 'pool'],
    price: 85,
    guests: 5,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/32415/',
  }),
  withImages('quinta-das-figueiras', {
    id: 16,
    title: 'Quinta das Figueiras',
    subtitle: 'Entre a natureza e a praia',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'garden'],
    price: 50,
    guests: 5,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/32984/',
  }),
  withImages('my-home-in-sesimbra', {
    id: 17,
    title: 'My Home in Sesimbra',
    subtitle: 'Casa perto do mar com vista para o castelo',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv', 'terrace'],
    price: 80,
    guests: 6,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/31937/',
  }),
  withImages('castle-apartment', {
    id: 19,
    title: 'Castle Apartment',
    subtitle: 'A vista mais bela do Castelo',
    location: 'Sesimbra',
    features: ['wifi', 'parking', 'tv', 'terrace'],
    price: 90,
    guests: 6,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/30834/',
  }),
  withImages('dolceplace', {
    id: 20,
    title: 'DolcePlace',
    subtitle: 'Casa perto da praia com varanda e vista mar',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'tv', 'seaView', 'terrace'],
    price: 90,
    guests: 6,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/28671/',
  }),
  withImages('casa-da-praia', {
    id: 21,
    title: 'Casa da Praia',
    subtitle: 'T2 a 2 min da praia com vista mar e BBQ',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv', 'seaView'],
    price: 75,
    guests: 6,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/28121/',
  }),
  withImages('seaflower-house', {
    id: 22,
    title: 'SeaFlower House',
    subtitle: 'Apartamento a 3 min a pé da praia',
    location: 'Sesimbra',
    features: ['beach', 'tv'],
    price: 60,
    guests: 6,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/27061/',
  }),
  withImages('ocean-sesimbra', {
    id: 23,
    title: 'Ocean Sesimbra',
    subtitle: 'Vista mar e 5 min a pé da praia',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'tv', 'seaView'],
    price: 80,
    guests: 6,
    bedrooms: 2,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/33763/',
  }),
  withImages('milady-house', {
    id: 24,
    title: 'Milady House',
    subtitle: 'Apartamento no centro da vila a 2 min da praia',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'tv', 'center'],
    price: 120,
    guests: 7,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/27612/',
  }),
  withImages('paradise-in-lagoa', {
    id: 25,
    title: 'Paradise in Lagoa',
    subtitle: 'Moradia na Lagoa de Albufeira com jardim e BBQ',
    location: 'Lagoa de Albufeira',
    features: ['beach', 'wifi', 'parking', 'tv', 'garden'],
    price: 120,
    guests: 7,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/27022/',
  }),
  withImages('retiro-d-alma', {
    id: 28,
    title: "Retiro D'Alma",
    subtitle: 'Jardim, BBQ e tranquilidade',
    location: 'Sesimbra',
    features: ['garden', 'beach', 'parking', 'wifi', 'tv'],
    price: 120,
    guests: 8,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/33398/',
  }),
  withImages('brisa-de-sesimbra', {
    id: 30,
    title: 'Brisa de Sesimbra',
    subtitle: 'T3 a 5 min a pé da Praia da Califórnia',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv'],
    price: 130,
    guests: 8,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/32094/',
  }),
  withImages('casa-campo-e-praia', {
    id: 31,
    title: 'Casa Campo e Praia - Meco',
    subtitle: 'Moradia V4 a 5 min da praia com jardim e BBQ',
    location: 'Sesimbra',
    features: ['beach', 'wifi', 'parking', 'tv', 'garden'],
    price: 180,
    guests: 8,
    bedrooms: 4,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/26572/',
  }),
  withImages('villa-pinheirinhos', {
    id: 32,
    title: 'Villa Pinheirinhos',
    subtitle: 'Natureza e praias selvagens',
    location: 'Sesimbra',
    features: ['wifi', 'parking', 'tv', 'garden'],
    price: 150,
    guests: 9,
    bedrooms: 3,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/31732/',
  }),
  withImages('villa-penim', {
    id: 35,
    title: 'Villa Penim',
    subtitle: 'Jacuzzi ao ar livre e jardim com BBQ',
    location: 'Sesimbra',
    features: ['garden', 'beach', 'parking', 'wifi', 'tv'],
    price: 200,
    guests: 10,
    bedrooms: 5,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/32918/',
  }),
];

export const accommodationsBySlug = Object.fromEntries(
  accommodations.map((accommodation) => [accommodation.slug, accommodation]),
) as Record<string, Accommodation>;
