// DolceStay Data Structures
// These can be connected to a CMS or WordPress in the future

export const BOOKING_URL = "https://reservas.dolcestay.com/pt-PT/rentals/";

export const contactInfo = {
  email: 'geral@dolcestay.com',
  phones: ['+351 968 442 646', '+351 925 407 035'],
  whatsapp: '+351968442646',
  address: {
    street: 'Av. da Liberdade n°58/60',
    postalCode: '2970-635',
    city: 'Sesimbra',
    country: 'Portugal',
  },
  social: {
    instagram: 'https://instagram.com/dolcestay',
    facebook: 'https://www.facebook.com/profile.php?id=61551128039116',
  },
};

export const featuredAccommodations = [
  {
    id: 1,
    title: 'Cantinho da Gingeira',
    subtitle: 'Casa a 5 min da Praia com Jardim e Churrasqueira',
    location: 'Sesimbra',
    image: '/images/accommodation-1.jpg',
    features: ['garden', 'beach', 'parking', 'wifi'] as const,
    price: 40,
    guests: 4,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/29065/',
  },
  {
    id: 2,
    title: 'Casa do Mário',
    subtitle: 'Studio a 50m da Praia de Sesimbra',
    location: 'Sesimbra',
    image: '/images/accommodation-2.jpg',
    features: ['beach', 'center', 'wifi'] as const,
    price: 55,
    guests: 2,
    bedrooms: 1,
    bookingUrl: 'https://reservas.dolcestay.com/pt-PT/rentals/25150/',
  },
  {
    id: 3,
    title: 'Villa Mar Azul',
    subtitle: 'Casa com Piscina e Vista Mar',
    location: 'Sesimbra',
    image: '/images/accommodation-3.jpg',
    features: ['seaView', 'pool', 'terrace', 'parking'] as const,
    price: 120,
    guests: 6,
    bedrooms: 3,
    bookingUrl: BOOKING_URL,
  },
  {
    id: 4,
    title: 'Apartamento Sesimbra Centro',
    subtitle: 'Apartamento Moderno no Centro',
    location: 'Sesimbra',
    image: '/images/accommodation-4.jpg',
    features: ['center', 'modern', 'wifi', 'aircon'] as const,
    price: 65,
    guests: 4,
    bedrooms: 2,
    bookingUrl: BOOKING_URL,
  },
];

export const testimonials = [
  {
    id: 1,
    text: 'O anfitrião responde muito rapidamente e é muito atencioso. O sítio é muito agradável, ideal para uns dias na praia. O apartamento não tem nada de desnecessário, apenas o básico, tudo o que é necessário para uns dias relaxantes.',
    author: 'João Pedro',
    location: 'Almada, Portugal',
    type: 'guest' as const,
    rating: 5,
  },
  {
    id: 2,
    text: 'Excelente experiência! A equipa da DolceStay tratou de tudo, desde a preparação do imóvel até à gestão das reservas. O rendimento do meu apartamento aumentou significativamente.',
    author: 'Maria Santos',
    location: 'Lisboa, Portugal',
    type: 'owner' as const,
    rating: 5,
  },
  {
    id: 3,
    text: 'Localização perfeita, a poucos minutos da praia. O apartamento estava impecável e a comunicação com a equipa foi excelente durante toda a estadia.',
    author: 'Pierre Dubois',
    location: 'Paris, France',
    type: 'guest' as const,
    rating: 5,
  },
  {
    id: 4,
    text: 'Finalmente posso rentabilizar o meu imóvel em Sesimbra sem preocupações. A DolceStay é muito profissional e os resultados são visíveis.',
    author: 'António Ferreira',
    location: 'Setúbal, Portugal',
    type: 'owner' as const,
    rating: 5,
  },
];

export const partnerExperiences = [
  {
    id: 1,
    name: 'Look Around Tours',
    category: 'experiences' as const,
    description: {
      pt: ['Jeep 4x4 tours', 'Tours culturais & Passeios pedestres', 'Observação dos golfinhos', 'Coastering & Escalada'],
      en: ['Jeep 4x4 tours', 'Cultural tours & Hiking', 'Dolphin watching', 'Coasteering & Climbing'],
      fr: ['Tours en Jeep 4x4', 'Tours culturels & Randonnées', 'Observation des dauphins', 'Coastering & Escalade'],
      es: ['Tours en Jeep 4x4', 'Tours culturales & Senderismo', 'Avistamiento de delfines', 'Coasteering & Escalada'],
      de: ['Jeep 4x4 Touren', 'Kulturtouren & Wanderungen', 'Delfinbeobachtung', 'Coasteering & Klettern'],
    },
    image: '/images/partner-lookaround.jpg',
    instagram: 'https://instagram.com/lookaroundtours',
    facebook: 'https://facebook.com/lookaroundtours',
    website: 'https://lookaroundtours.com/',
  },
  {
    id: 2,
    name: 'Our Roots',
    category: 'experiences' as const,
    description: {
      pt: ['Canoagem', 'Kayak tours', 'Stand up paddle', 'Passeios de barco'],
      en: ['Canoeing', 'Kayak tours', 'Stand up paddle', 'Boat trips'],
      fr: ['Canoë', 'Tours en kayak', 'Stand up paddle', 'Promenades en bateau'],
      es: ['Piragüismo', 'Tours en kayak', 'Stand up paddle', 'Paseos en barco'],
      de: ['Kanufahren', 'Kajaktouren', 'Stand up paddle', 'Bootsfahrten'],
    },
    image: '/images/partner-ourroots.jpg',
    instagram: 'https://instagram.com/ourroots',
    facebook: 'https://facebook.com/ourroots',
    website: 'https://cipreiadiveclub.com/',
  },
  {
    id: 3,
    name: 'Sesimbra SUP Rentals',
    category: 'experiences' as const,
    description: {
      pt: ['Aluguer de pranchas de Paddle', 'Receba a prancha na sua morada', 'Desembale, insufle e entre na água!'],
      en: ['Paddle board rental', 'Board delivered to your address', 'Unpack, inflate and dive in!'],
      fr: ['Location de planches de paddle', 'Planche livrée à votre adresse', 'Déballez, gonflez et plongez!'],
      es: ['Alquiler de tablas de paddle', 'Tabla entregada en su dirección', '¡Desempaquete, infle y entre al agua!'],
      de: ['Paddelbrett-Verleih', 'Brett wird zu Ihrer Adresse geliefert', 'Auspacken, aufblasen und ins Wasser!'],
    },
    image: '/images/partner-sup.jpg',
    instagram: 'https://instagram.com/sesimbrasup',
    website: 'https://sesimbrasuprentals.com/',
  },
  {
    id: 4,
    name: 'Cipreia Dive Club',
    category: 'experiences' as const,
    description: {
      pt: ['Batismo de mergulho', 'Saídas de Mergulho', 'Cursos vários'],
      en: ['Diving baptism', 'Diving excursions', 'Various courses'],
      fr: ['Baptême de plongée', 'Sorties de plongée', 'Divers cours'],
      es: ['Bautismo de buceo', 'Salidas de buceo', 'Varios cursos'],
      de: ['Tauch-Taufe', 'Tauchausflüge', 'Verschiedene Kurse'],
    },
    image: '/images/partner-cipreia.jpg',
    instagram: 'https://instagram.com/cipreiadive',
    facebook: 'https://facebook.com/cipreiadive',
    website: 'https://cipreiadiveclub.com/',
  },
  {
    id: 5,
    name: 'Pexitos',
    category: 'experiences' as const,
    description: {
      pt: ['Excursões Culturais', 'Excursões por patrimónios históricos', 'Excursões pedestres'],
      en: ['Cultural excursions', 'Historical heritage tours', 'Hiking excursions'],
      fr: ['Excursions culturelles', 'Visites du patrimoine historique', 'Excursions de randonnée'],
      es: ['Excursiones culturales', 'Excursiones por patrimonio histórico', 'Excursiones de senderismo'],
      de: ['Kulturausflüge', 'Ausflüge zum historischen Erbe', 'Wanderausflüge'],
    },
    image: '/images/partner-pexitos.jpg',
    instagram: 'https://instagram.com/pexitos',
    facebook: 'https://facebook.com/pexitos',
    website: 'https://www.wearepexitos.com/',
  },
  {
    id: 6,
    name: 'Seatru',
    category: 'experiences' as const,
    description: {
      pt: ['Clear Kayak Experience', 'Aluguer de kayaks', 'Tours personalizadas'],
      en: ['Clear Kayak Experience', 'Kayak rental', 'Personalized tours'],
      fr: ['Expérience Kayak Transparent', 'Location de kayaks', 'Tours personnalisés'],
      es: ['Experiencia Kayak Transparente', 'Alquiler de kayaks', 'Tours personalizados'],
      de: ['Clear Kayak Erlebnis', 'Kajak-Verleih', 'Personalisierte Touren'],
    },
    image: '/images/partner-seatru.jpg',
    instagram: 'https://instagram.com/seatru',
    website: 'https://www.seatru.eu/',
  },
];

export const partnerRestaurants = [
  {
    id: 7,
    name: 'Gliese',
    category: 'restaurants' as const,
    type: 'bar' as const,
    image: '/images/partner-gliese.jpg',
    website: 'https://www.tripadvisor.pt/Restaurant_Review-g227946-d20074683-Reviews-Gliese_Restaurante_Bar-Sesimbra_Setubal_District_Alentejo.html',
  },
  {
    id: 8,
    name: 'O Batel',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-batel.jpg',
    website: 'https://www.tripadvisor.pt/Restaurant_Review-g227946-d23432167-Reviews-O_Batel-Sesimbra_Setubal_District_Alentejo.html',
  },
  {
    id: 9,
    name: 'O Zagaia',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-zagaia.jpg',
    website: 'https://www.tripadvisor.pt/Restaurant_Review-g227946-d17188917-Reviews-O_Zagaia-Sesimbra_Setubal_District_Alentejo.html',
  },
  {
    id: 10,
    name: 'Casa Mateus',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-casamateus.jpg',
    website: 'https://www.casamateus.pt/',
  },
  {
    id: 11,
    name: 'Tasca do 13',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-tasca13.jpg',
    website: 'https://www.tripadvisor.pt/Restaurant_Review-g227946-d4136825-Reviews-Tasca_do_13-Sesimbra_Setubal_District_Alentejo.html',
  },
  {
    id: 12,
    name: 'Onda Selvagem',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-ondaselvagem.jpg',
    website: 'https://ondaselvagem.com/',
  },
  {
    id: 13,
    name: 'A Sesimbrense',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-sesimbrense.jpg',
    website: 'https://restauranteasesimbrense.eatbu.com/?lang=pt',
  },
  {
    id: 14,
    name: 'Isaías',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-isaias.jpg',
    website: 'https://www.tripadvisor.pt/Restaurant_Review-g227946-d3169993-Reviews-Taberna_Isaias-Sesimbra_Setubal_District_Alentejo.html',
  },
  {
    id: 15,
    name: 'Vidal Food and Drinks',
    category: 'restaurants' as const,
    type: 'bar' as const,
    image: '/images/partner-vidal.jpg',
    website: 'https://www.instagram.com/vidalfood_and_drinks/',
  },
  {
    id: 16,
    name: 'Restaurante Maré',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-mare.jpg',
    website: 'https://restaurantemaresesimbra.eatbu.com/?lang=pt',
  },
  {
    id: 17,
    name: 'Bar do Peixe - Meco',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-bardopeixe.jpg',
    website: 'https://www.bardopeixe.pt/',
  },
  {
    id: 18,
    name: 'Gelatomania',
    category: 'restaurants' as const,
    type: 'gelataria' as const,
    image: '/images/partner-gelatomania.jpg',
    website: 'https://gelatomania.pt/',
  },
  {
    id: 19,
    name: 'Ribamar',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-ribamar.jpg',
    website: 'https://www.restaurante-ribamar.pt/',
  },
  {
    id: 20,
    name: "Fun Friends n'Fandango",
    category: 'restaurants' as const,
    type: 'bar' as const,
    image: '/images/partner-fandango.jpg',
    website: 'https://www.instagram.com/fandangosesimbra/',
  },
  {
    id: 21,
    name: 'Virgilinda',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-virgilinda.jpg',
    website: 'https://www.tripadvisor.pt/Restaurant_Review-g227946-d7225471-Reviews-Restaurante_a_Virgilinda-Sesimbra_Setubal_District_Alentejo.html',
  },
  {
    id: 22,
    name: 'O Velho e o Mar',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-velhoeomar.jpg',
    website: 'https://restauranteovelhoeomar.com/',
  },
  {
    id: 23,
    name: 'O Golfinho',
    category: 'restaurants' as const,
    type: 'restaurant' as const,
    image: '/images/partner-golfinho.jpg',
    website: 'https://www.tripadvisor.pt/Restaurant_Review-g227946-d7372042-Reviews-O_Golfinho-Sesimbra_Setubal_District_Alentejo.html',
  },
];

export const services = [
  {
    id: 'bookingManagement',
    icon: 'Calendar',
  },
  {
    id: 'checkInOut',
    icon: 'Key',
  },
  {
    id: 'cleaning',
    icon: 'Sparkles',
  },
  {
    id: 'pricing',
    icon: 'TrendingUp',
  },
  {
    id: 'guestSupport',
    icon: 'Headphones',
  },
  {
    id: 'marketing',
    icon: 'Megaphone',
  },
  {
    id: 'maintenance',
    icon: 'Wrench',
  },
  {
    id: 'preparation',
    icon: 'Home',
  },
];
