import type { Language } from './translations';

export type TestimonialItem = {
  author: string;
  location: string;
  type: 'guest';
  rating: 5;
  text: string;
};

type LocalizedText = Record<Language, string>;

const country = {
  portugal: { pt: 'Portugal', en: 'Portugal', fr: 'Portugal', es: 'Portugal', de: 'Portugal' },
  france: { pt: 'França', en: 'France', fr: 'France', es: 'Francia', de: 'Frankreich' },
  spain: { pt: 'Espanha', en: 'Spain', fr: 'Espagne', es: 'España', de: 'Spanien' },
  uk: { pt: 'Reino Unido', en: 'United Kingdom', fr: 'Royaume-Uni', es: 'Reino Unido', de: 'Vereinigtes Königreich' },
  usa: { pt: 'Estados Unidos', en: 'United States', fr: 'États-Unis', es: 'Estados Unidos', de: 'Vereinigte Staaten' },
  italy: { pt: 'Itália', en: 'Italy', fr: 'Italie', es: 'Italia', de: 'Italien' },
  poland: { pt: 'Polónia', en: 'Poland', fr: 'Pologne', es: 'Polonia', de: 'Polen' },
  qatar: { pt: 'Catar', en: 'Qatar', fr: 'Qatar', es: 'Catar', de: 'Katar' },
  canada: { pt: 'Canadá', en: 'Canada', fr: 'Canada', es: 'Canadá', de: 'Kanada' },
  germany: { pt: 'Alemanha', en: 'Germany', fr: 'Allemagne', es: 'Alemania', de: 'Deutschland' },
  netherlands: { pt: 'Países Baixos', en: 'Netherlands', fr: 'Pays-Bas', es: 'Países Bajos', de: 'Niederlande' },
} as const satisfies Record<string, LocalizedText>;

type CountryKey = keyof typeof country;

type TestimonialDefinition = {
  id: string;
  propertyKey: string;
  author: string;
  country: CountryKey;
  text: LocalizedText;
};

const defineTestimonial = (
  id: string,
  propertyKey: string,
  author: string,
  countryKey: CountryKey,
  text: LocalizedText,
): TestimonialDefinition => ({ id, propertyKey, author, country: countryKey, text });

/** Real guest reviews sourced from the project Reviews folder. */
export const testimonialDefinitions: readonly TestimonialDefinition[] = [
  defineTestimonial('trevo-beach-house-tiago', 'trevo-beach-house', 'Tiago', 'portugal', {
    pt: 'Tive uma experiência excelente neste Airbnb. A comunicação foi impecável, respondiam sempre muito rápido e mostraram-se bastante flexíveis ao longo de toda a estadia. Foram super acessíveis e fáceis de lidar, o que fez toda a diferença. Quanto à casa, simplesmente incrível, muito limpa, bem cuidada, confortável e ainda melhor do que nas fotos. Recomendo!',
    en: 'I had an excellent experience at this Airbnb. Communication was impeccable — they always responded very quickly and were very flexible throughout the stay. They were super approachable and easy to deal with, which made all the difference. As for the house, simply incredible: very clean, well maintained, comfortable, and even better than in the photos. I recommend it!',
    fr: 'J\'ai vécu une excellente expérience dans ce logement Airbnb. La communication était impeccable, ils répondaient toujours très rapidement et se sont montrés très flexibles tout au long du séjour. Super accessibles et faciles à vivre, ce qui a fait toute la différence. Quant à la maison, tout simplement incroyable : très propre, bien entretenue, confortable et encore mieux que sur les photos. Je recommande !',
    es: 'Tuve una experiencia excelente en este alojamiento de Airbnb. La comunicación fue impecable, siempre respondían muy rápido y fueron muy flexibles durante toda la estancia. Fueron muy accesibles y fáciles de tratar, lo que marcó la diferencia. En cuanto a la casa, simplemente increíble: muy limpia, bien cuidada, cómoda e incluso mejor que en las fotos. ¡Lo recomiendo!',
    de: 'Ich hatte eine hervorragende Erfahrung in diesem Airbnb. Die Kommunikation war tadellos, sie antworteten immer sehr schnell und waren während des gesamten Aufenthalts sehr flexibel. Super zugänglich und unkompliziert — das hat den Unterschied gemacht. Das Haus ist einfach unglaublich: sehr sauber, gepflegt, komfortabel und noch besser als auf den Fotos. Sehr empfehlenswert!',
  }),
  defineTestimonial('casa-da-falesia-yasmina', 'casa-da-falesia', 'Yasmina', 'france', {
    pt: 'Uma receção muito calorosa e um ambiente incrível! Adormecer ao som das ondas e acordar com uma vista destas não tem preço! Obrigado ao Jorge pela sua gentileza e bom humor! Voltaria.',
    en: 'A very warm welcome and an incredible atmosphere! Falling asleep to the sound of the waves and waking up to a view like this is priceless! Thanks to Jorge for his kindness and good humour! I would return.',
    fr: 'Un accueil très chaleureux et une ambiance incroyable ! S\'endormir au bruit des vagues et se réveiller avec une vue pareille n\'a pas de prix ! Merci à Jorge pour sa gentillesse et son bon humour ! J\'y retournerais.',
    es: '¡Una acogida muy cálida y un ambiente increíble! Dormir con el sonido de las olas y despertar con unas vistas así no tiene precio. ¡Gracias a Jorge por su amabilidad y buen humor! Volvería.',
    de: 'Ein sehr herzlicher Empfang und eine unglaubliche Atmosphäre! Mit dem Rauschen der Wellen einzuschlafen und mit so einer Aussicht aufzuwachen ist unbezahlbar! Danke an Jorge für seine Freundlichkeit und gute Laune! Ich würde wiederkommen.',
  }),
  defineTestimonial('casa-campo-e-praia-francisco-javier', 'casa-campo-e-praia', 'Francisco Javier', 'spain', {
    pt: 'Alojamento imbatível!!! Comunicação maravilhosa e completa com o anfitrião. A casa está muito limpa!!! Estivemos lá por pouco tempo, mas foi certamente muito agradável em todos os sentidos. Obrigado.',
    en: 'Unbeatable accommodation!!! Wonderful and complete communication with the host. The house is very clean!!! We were there for a short time, but it was certainly very pleasant in every way. Thank you.',
    fr: 'Hébergement imbattable !!! Communication merveilleuse et complète avec l\'hôte. La maison est très propre !!! Nous y sommes restés peu de temps, mais ce fut très agréable à tous les égards. Merci.',
    es: '¡Alojamiento imbatible! Comunicación maravillosa y completa con el anfitrión. La casa está muy limpia. Estuvimos poco tiempo, pero fue muy agradable en todos los sentidos. Gracias.',
    de: 'Unschlagbare Unterkunft!!! Wunderbare und vollständige Kommunikation mit dem Gastgeber. Das Haus ist sehr sauber!!! Wir waren nur kurz da, aber es war in jeder Hinsicht sehr angenehm. Danke.',
  }),
  defineTestimonial('casa-do-dario-carolina', 'casa-do-dario', 'Carolina', 'portugal', {
    pt: 'A minha estadia foi mais do que eu imaginava, a localização perto do mar, tudo funcionava no apartamento, pessoas muito simpáticas, anfitrião super atencioso, senti-me realmente em casa, a tranquilidade do lugar, ouvir apenas o barulho do mar ao dormir, é, para aqueles de nós que gostam do mar, algo espetacular. Só tenho coisas boas a dizer sobre este lugar, FANTÁSTICO!! Espero voltar em breve.',
    en: 'My stay was more than I imagined — the location near the sea, everything worked in the apartment, very friendly people, a super attentive host, I truly felt at home. The tranquillity of the place, hearing only the sound of the sea while sleeping, is spectacular for those of us who love the sea. I only have good things to say about this place — FANTASTIC!! I hope to return soon.',
    fr: 'Mon séjour a dépassé mes attentes : emplacement près de la mer, tout fonctionnait dans l\'appartement, des personnes très sympathiques, un hôte super attentionné, je me suis vraiment sentie chez moi. La tranquillité du lieu, n\'entendre que le bruit de la mer en dormant, c\'est spectaculaire pour ceux qui aiment la mer. Je n\'ai que du bien à dire sur cet endroit — FANTASTIQUE !! J\'espère revenir bientôt.',
    es: 'Mi estancia superó lo que imaginaba: ubicación cerca del mar, todo funcionaba en el apartamento, gente muy amable, anfitrión super atento, me sentí realmente como en casa. La tranquilidad del lugar, escuchar solo el sonido del mar al dormir, es espectacular para quienes amamos el mar. Solo tengo cosas buenas que decir de este lugar — ¡FANTÁSTICO! Espero volver pronto.',
    de: 'Mein Aufenthalt war mehr als ich mir vorgestellt hatte — die Lage nahe am Meer, alles funktionierte in der Wohnung, sehr freundliche Menschen, ein super aufmerksamer Gastgeber, ich fühlte mich wirklich wie zu Hause. Die Ruhe des Ortes, beim Einschlafen nur das Rauschen des Meeres zu hören, ist für Meeresliebhaber etwas Spektakuläres. Ich habe nur Gutes über diesen Ort zu sagen — FANTASTISCH!! Ich hoffe, bald zurückzukehren.',
  }),
  defineTestimonial('casa-da-lagoa-pedro', 'casa-da-lagoa', 'Pedro', 'uk', {
    pt: 'Passámos uma semana maravilhosa nesta casa. O jardim era bonito e agradável, com vistas deslumbrantes. Gostámos particularmente do fácil acesso à lagoa, o que tornou a nossa estadia ainda mais especial. A equipa foi incrivelmente simpática e prestável, garantindo que tínhamos tudo o que precisávamos. Recomendamos vivamente este local para uma escapadela relaxante.',
    en: 'We had a lovely week at this house. The garden was beautiful and pleasant, offering stunning views. We particularly enjoyed the easy access to the lagoon, which made our stay even more special. The staff were incredibly nice and helpful, ensuring we had everything we needed. We highly recommend this place for a relaxing getaway.',
    fr: 'Nous avons passé une merveilleuse semaine dans cette maison. Le jardin était beau et agréable, avec des vues magnifiques. Nous avons particulièrement apprécié l\'accès facile à la lagune, ce qui a rendu notre séjour encore plus spécial. L\'équipe était incroyablement sympathique et serviable. Nous recommandons vivement cet endroit pour une escapade relaxante.',
    es: 'Pasamos una semana maravillosa en esta casa. El jardín era bonito y agradable, con unas vistas impresionantes. Disfrutamos especialmente del fácil acceso a la laguna, lo que hizo nuestra estancia aún más especial. El equipo fue increíblemente amable y servicial. Recomendamos encarecidamente este lugar para una escapada relajante.',
    de: 'Wir verbrachten eine wunderbare Woche in diesem Haus. Der Garten war schön und angenehm mit atemberaubender Aussicht. Besonders gut gefiel uns der einfache Zugang zur Lagune. Das Team war unglaublich freundlich und hilfsbereit. Wir empfehlen diesen Ort wärmstens für einen entspannten Kurzurlaub.',
  }),
  defineTestimonial('olive-tree-house-david', 'olive-tree-house', 'David', 'spain', {
    pt: 'Alojamento fantástico para ir em família! A casa era ótima, muito limpa e com muito espaço para as crianças. Passámos uns dias maravilhosos e sentimo-nos em casa. O atendimento do anfitrião foi excelente. Totalmente recomendada!',
    en: 'Fantastic accommodation for a family trip! The house was great, very clean and with plenty of space for the children. We spent wonderful days and felt at home. The host\'s service was excellent. Totally recommended!',
    fr: 'Hébergement fantastique pour un séjour en famille ! La maison était superbe, très propre et avec beaucoup d\'espace pour les enfants. Nous avons passé des jours merveilleux et nous nous sommes sentis chez nous. Le service de l\'hôte était excellent. Totalement recommandé !',
    es: '¡Alojamiento fantástico para ir en familia! La casa era estupenda, muy limpia y con mucho espacio para los niños. Pasamos unos días maravillosos y nos sentimos como en casa. La atención del anfitrión fue excelente. ¡Totalmente recomendado!',
    de: 'Fantastische Unterkunft für einen Familienurlaub! Das Haus war großartig, sehr sauber und mit viel Platz für die Kinder. Wir verbrachten wunderbare Tage und fühlten uns wie zu Hause. Der Service des Gastgebers war ausgezeichnet. Absolut empfehlenswert!',
  }),
  defineTestimonial('paradise-in-lagoa-riaz', 'paradise-in-lagoa', 'Riaz', 'uk', {
    pt: 'Propriedade encantadora perto de uma enorme praia fabulosa. Ótima área de churrasco ao ar livre. O Luís, o Jorge e a equipa da DolceStay merecem uma menção especial. Foram super flexíveis com os horários de check-in e check-out, o que fez realmente a diferença.',
    en: 'Charming property near a huge fabulous beach. Great outdoor barbecue area. Luís, Jorge and the DolceStay team deserve a special mention. They were super flexible with check-in and check-out times, which really made a difference.',
    fr: 'Propriété charmante près d\'une immense plage fabuleuse. Superbe espace barbecue en plein air. Luís, Jorge et l\'équipe DolceStay méritent une mention spéciale. Ils ont été super flexibles avec les horaires d\'arrivée et de départ, ce qui a vraiment fait la différence.',
    es: 'Propiedad encantadora cerca de una enorme playa fabulosa. Excelente zona de barbacoa al aire libre. Luís, Jorge y el equipo de DolceStay merecen una mención especial. Fueron muy flexibles con los horarios de check-in y check-out, lo que marcó la diferencia.',
    de: 'Charmante Unterkunft in der Nähe eines riesigen, wunderbaren Strandes. Toller Grillbereich im Freien. Luís, Jorge und das DolceStay-Team verdienen besondere Erwähnung. Sie waren super flexibel bei Check-in- und Check-out-Zeiten — das hat wirklich den Unterschied gemacht.',
  }),
  defineTestimonial('casa-da-praia-ana-paula', 'casa-da-praia', 'Ana Paula', 'portugal', {
    pt: 'Ótimo. Senti-me imediatamente confortável lá. Tem tudo o que necessita. Pensaram em tudo. Íamos a pé para a praia todos os dias com as crianças. Apartamento muito agradável. São todos muito simpáticos. Foi muito bom. Obrigado por isso.',
    en: 'Great. I felt immediately comfortable there. It has everything you need. They thought of everything. We walked to the beach every day with the children. Very pleasant apartment. Everyone is very friendly. It was very good. Thank you for that.',
    fr: 'Super. Je me suis sentie immédiatement à l\'aise. Il y a tout ce qu\'il faut. On a tout prévu. Nous allions à la plage à pied tous les jours avec les enfants. Appartement très agréable. Tout le monde est très sympathique. C\'était très bien. Merci.',
    es: 'Genial. Me sentí cómoda de inmediato. Tiene todo lo necesario. Pensaron en todo. Íbamos a pie a la playa todos los días con los niños. Apartamento muy agradable. Todos son muy amables. Fue muy bueno. Gracias por ello.',
    de: 'Großartig. Ich fühlte mich sofort wohl. Es hat alles, was man braucht. An alles wurde gedacht. Wir gingen jeden Tag mit den Kindern zu Fuß zum Strand. Sehr angenehme Wohnung. Alle sind sehr freundlich. Es war sehr gut. Danke dafür.',
  }),
  defineTestimonial('refugio-chris', 'refugio', 'Chris', 'usa', {
    pt: 'Ponto de partida perfeito para 2 dias em Sesimbra com os meus pais. Os anfitriões foram extremamente comunicativos e prestáveis em tudo, desde encontrar um lugar de estacionamento até às melhores recomendações de restaurantes. Fica a uma curta caminhada da praia e da zona principal de Sesimbra, e adorámos tomar o pequeno-almoço no terraço.',
    en: 'Perfect landing pad for 2 days in Sesimbra with my parents. The hosts were extremely communicative and helpful with everything from finding a parking spot to giving us the best restaurant recommendations. It\'s a short walk to the beach and the main strip in Sesimbra, and we loved eating breakfast on the roof deck.',
    fr: 'Point de départ parfait pour 2 jours à Sesimbra avec mes parents. Les hôtes étaient extrêmement communicatifs et serviables pour tout, de la recherche d\'une place de parking aux meilleures recommandations de restaurants. À quelques minutes à pied de la plage et du centre de Sesimbra, nous avons adoré prendre le petit-déjeuner sur le toit-terrasse.',
    es: 'Punto de partida perfecto para 2 días en Sesimbra con mis padres. Los anfitriones fueron extremadamente comunicativos y serviciales en todo, desde encontrar aparcamiento hasta las mejores recomendaciones de restaurantes. A poca distancia a pie de la playa y del centro de Sesimbra, y nos encantó desayunar en la terraza.',
    de: 'Perfekter Ausgangspunkt für 2 Tage in Sesimbra mit meinen Eltern. Die Gastgeber waren äußerst kommunikativ und hilfsbereit — vom Parkplatz bis zu den besten Restaurantempfehlungen. Kurzer Fußweg zum Strand und zur Hauptstraße in Sesimbra, und wir liebten das Frühstück auf der Dachterrasse.',
  }),
  defineTestimonial('vila-das-conchas-marta', 'vila-das-conchas', 'Marta', 'portugal', {
    pt: 'Casa super bem localizada, perto da praia e restaurantes. Bastante estacionamento no interior do condomínio. Boa zona de piscina. Cozinha bastante bem equipada, a casa tem todas as comodidades necessárias e estava limpa e arrumada. De realçar a disponibilidade da equipa, excelente comunicação e cuidado! Muito obrigada!',
    en: 'House super well located, near the beach and restaurants. Plenty of parking inside the condominium. Good pool area. Kitchen very well equipped, the house has all the necessary amenities and was clean and tidy. Highlighting the team\'s availability, excellent communication and care! Thank you very much!',
    fr: 'Maison super bien située, près de la plage et des restaurants. Beaucoup de places de parking dans la résidence. Bonne zone piscine. Cuisine très bien équipée, la maison a toutes les commodités nécessaires et était propre et rangée. À souligner la disponibilité de l\'équipe, excellente communication et attention ! Merci beaucoup !',
    es: 'Casa muy bien ubicada, cerca de la playa y restaurantes. Mucho aparcamiento dentro del condominio. Buena zona de piscina. Cocina muy bien equipada, la casa tiene todas las comodidades necesarias y estaba limpia y ordenada. Destacar la disponibilidad del equipo, excelente comunicación y cuidado. ¡Muchas gracias!',
    de: 'Haus super gut gelegen, nahe Strand und Restaurants. Viel Parkplatz innerhalb der Anlage. Schöner Poolbereich. Küche sehr gut ausgestattet, das Haus hat alle nötigen Annehmlichkeiten und war sauber und ordentlich. Besonders hervorzuheben: die Verfügbarkeit des Teams, exzellente Kommunikation und Fürsorge! Vielen Dank!',
  }),
  defineTestimonial('casa-atlas-francisco-neto', 'casa-atlas', 'Francisco Neto', 'portugal', {
    pt: 'Estadia bastante agradável, a começar pelo anfitrião que a todo momento não deixou faltar qualquer informação e sempre muito atencioso. No imóvel a surpresa continua, impecavelmente limpo, organizado, não faltou nada para os hóspedes. O local é mágico, perto de diversos restaurantes, comércio e serviço em geral. O estacionamento é bem fácil e seguro. Certamente iremos voltar.',
    en: 'Very pleasant stay, starting with the host who at all times provided every bit of information and was always very attentive. The property continues to impress — impeccably clean, organized, nothing was missing for the guests. The location is magical, close to various restaurants, shops and services. Parking is very easy and safe. We will certainly return.',
    fr: 'Séjour très agréable, à commencer par l\'hôte qui à tout moment a fourni toutes les informations et a toujours été très attentionné. Le logement continue d\'impressionner — impeccablement propre, organisé, rien ne manquait aux hôtes. L\'endroit est magique, près de nombreux restaurants, commerces et services. Le parking est facile et sûr. Nous reviendrons certainement.',
    es: 'Estancia muy agradable, empezando por el anfitrión que en todo momento no dejó faltar información y siempre fue muy atento. En el inmueble la sorpresa continúa: impecablemente limpio, organizado, no faltó nada para los huéspedes. El lugar es mágico, cerca de varios restaurantes, comercio y servicios. El aparcamiento es fácil y seguro. Sin duda volveremos.',
    de: 'Sehr angenehmer Aufenthalt, beginnend mit dem Gastgeber, der jederzeit alle Informationen gab und immer sehr aufmerksam war. Die Unterkunft überzeugt weiter — tadellos sauber, organisiert, den Gästen fehlte nichts. Die Lage ist magisch, nahe verschiedener Restaurants, Geschäfte und Dienstleistungen. Parken ist einfach und sicher. Wir werden sicher wiederkommen.',
  }),
  defineTestimonial('milady-house-ana', 'milady-house', 'Ana', 'uk', {
    pt: 'Divertimo-nos imenso em Sesimbra. A DolceStay foi o espaço perfeito para nós. Podíamos ir a qualquer lugar a pé a partir daqui. Ótima padaria e pequeno supermercado com tudo o que era necessário ao virar da esquina. A uma curta distância a pé da praia, do mercado, de restaurantes e de cafés. A casa corresponde à descrição e foi perfeita para as nossas férias. A varanda e as grandes janelas e portas eram adoráveis — um momento tão agradável quando tomámos o nosso café de manhã a olhar para fora. Definitivamente voltaríamos. Os anfitriões foram super simpáticos e prestáveis. A comunicação foi perfeita.',
    en: 'We had a great time in Sesimbra. DolceStay was the perfect place for us. We could walk anywhere from here. Great bakery and small supermarket with all that was needed just around the corner. Short walk to the beach, the market, restaurants, coffee shops. The house matches the description and was perfect for our holiday. The balcony and the big windows and doors were lovely — such a nice moment when we had our coffee in the morning looking outside. We would definitely come back. The hosts were super friendly and helpful. Communication was perfect.',
    fr: 'Nous avons passé un excellent moment à Sesimbra. DolceStay était l\'endroit parfait pour nous. Nous pouvions aller partout à pied. Excellente boulangerie et petite épicerie à deux pas. À quelques minutes à pied de la plage, du marché, des restaurants et cafés. La maison correspond à la description et était parfaite pour nos vacances. Le balcon et les grandes fenêtres étaient adorables. Nous reviendrions sans hésiter. Les hôtes étaient super sympathiques et serviables. Communication parfaite.',
    es: 'Lo pasamos genial en Sesimbra. DolceStay fue el lugar perfecto para nosotros. Podíamos ir a cualquier sitio a pie. Excelente panadería y pequeño supermercado a la vuelta de la esquina. A poca distancia a pie de la playa, el mercado, restaurantes y cafés. La casa coincide con la descripción y fue perfecta para nuestras vacaciones. El balcón y las grandes ventanas eran encantadores. Sin duda volveríamos. Los anfitriones fueron super amables y serviciales. Comunicación perfecta.',
    de: 'Wir hatten eine tolle Zeit in Sesimbra. DolceStay war der perfekte Ort für uns. Von hier aus konnten wir überall zu Fuß hingehen. Tolle Bäckerei und kleiner Supermarkt um die Ecke. Kurzer Fußweg zum Strand, Markt, Restaurants und Cafés. Das Haus entspricht der Beschreibung und war perfekt für unseren Urlaub. Der Balkon und die großen Fenster waren herrlich. Wir würden definitiv wiederkommen. Die Gastgeber waren super freundlich und hilfsbereit. Kommunikation war perfekt.',
  }),
  defineTestimonial('my-home-aurora', 'my-home', 'Aurora Xica', 'qatar', {
    pt: 'Tivemos uma estadia maravilhosa neste alojamento. O espaço está absolutamente impecável e muito bem equipado, perfeito para uma estadia mais longa. Ficámos em família durante algumas semanas e sentimo-nos verdadeiramente em casa desde o momento em que chegámos. A equipa foi incrivelmente acolhedora, profissional e amigável durante toda a estadia. Estiveram sempre disponíveis e rápidos a ajudar no que fosse necessário. Gostámos genuinamente da nossa estadia e voltaríamos com prazer.',
    en: 'We had a wonderful stay at this Airbnb. The place is absolutely spotless and very well equipped, making it perfect for a longer stay. We stayed as a family for a few weeks and truly felt right at home from the moment we arrived. The team was incredibly welcoming, professional, and friendly throughout our stay. They were always responsive and quick to assist with anything we needed. We genuinely enjoyed our stay and would happily return.',
    fr: 'Nous avons passé un merveilleux séjour dans ce logement. L\'endroit est absolument impeccable et très bien équipé, parfait pour un séjour plus long. Nous sommes restés en famille pendant quelques semaines et nous nous sommes sentis chez nous dès notre arrivée. L\'équipe était incroyablement accueillante, professionnelle et amicale. Toujours disponibles et rapides à aider. Nous avons vraiment apprécié notre séjour et reviendrions avec plaisir.',
    es: 'Tuvimos una estancia maravillosa en este alojamiento. El lugar está absolutamente impecable y muy bien equipado, perfecto para una estancia más larga. Nos quedamos en familia durante unas semanas y nos sentimos como en casa desde el momento en que llegamos. El equipo fue increíblemente acogedor, profesional y amable. Siempre disponibles y rápidos para ayudar. Disfrutamos genuinamente de nuestra estancia y volveríamos con gusto.',
    de: 'Wir hatten einen wunderbaren Aufenthalt in dieser Unterkunft. Der Ort ist absolut makellos und sehr gut ausgestattet — perfekt für einen längeren Aufenthalt. Wir blieben als Familie einige Wochen und fühlten uns vom ersten Moment an wie zu Hause. Das Team war unglaublich einladend, professionell und freundlich. Immer erreichbar und schnell behilflich. Wir haben unseren Aufenthalt wirklich genossen und würden gerne wiederkommen.',
  }),
  defineTestimonial('sesimbra-beach-apartment-louise', 'sesimbra-beach-apartment', 'Louise', 'france', {
    pt: 'Tivemos uma estadia incrível! Relação qualidade-preço fantástica. Sentimo-nos em casa. Tudo super confortável (cama, pressão do chuveiro). O terraço com a pequena vista era um sonho. Raramente fico num lugar de tanta qualidade, especialmente no Airbnb. A vila também é um paraíso. O Jorge foi super proativo, disponível e flexível. Recomendaria este lugar de olhos fechados e voltaria no próximo ano sem hesitar. Obrigada!',
    en: 'We had an amazing stay! Incredible value for money. We felt at home. Everything super comfy (bed, shower pressure). The terrace with the little view was a dream. I rarely stay in such quality place, especially on Airbnb. The town also is just paradise. Jorge was super proactive, available, and flexible. I would recommend this place my eyes closed and would come next year without hesitation. Thank you so much!',
    fr: 'Nous avons passé un séjour incroyable ! Rapport qualité-prix fantastique. Nous nous sommes sentis chez nous. Tout super confortable (lit, pression de la douche). La terrasse avec la petite vue était un rêve. Je séjourne rarement dans un endroit de si bonne qualité, surtout sur Airbnb. La ville est un paradis. Jorge a été super proactif, disponible et flexible. Je recommanderais les yeux fermés et reviendrais l\'année prochaine sans hésiter. Merci !',
    es: '¡Tuvimos una estancia increíble! Relación calidad-precio fantástica. Nos sentimos como en casa. Todo super cómodo (cama, presión de la ducha). La terraza con la pequeña vista era un sueño. Rara vez me alojo en un lugar de tanta calidad, especialmente en Airbnb. El pueblo también es un paraíso. Jorge fue super proactivo, disponible y flexible. Recomendaría este lugar con los ojos cerrados y volvería el próximo año sin dudarlo. ¡Gracias!',
    de: 'Wir hatten einen fantastischen Aufenthalt! Unglaubliches Preis-Leistungs-Verhältnis. Wir fühlten uns wie zu Hause. Alles super gemütlich (Bett, Duschdruck). Die Terrasse mit dem kleinen Ausblick war ein Traum. Ich übernachte selten an so einem qualitativ hochwertigen Ort, besonders auf Airbnb. Die Stadt ist ein Paradies. Jorge war super proaktiv, verfügbar und flexibel. Ich würde diese Unterkunft blind empfehlen und nächstes Jahr ohne zu zögern wiederkommen. Vielen Dank!',
  }),
  defineTestimonial('sesimbra-beach-apartment-matteo', 'sesimbra-beach-apartment', 'Matteo', 'italy', {
    pt: 'O Luís foi muito gentil. Devido a um atraso no voo, chegámos muito tarde, e ele esperou por nós para nos dar as chaves, ajudando-nos também a levar as malas para o apartamento. Foi simpático e amigável e também tivemos uma conversa muito agradável. O apartamento é muito agradável e bem conservado, com uma cozinha equipada e tudo muito limpo. O pequeno terraço tem uma vista esplêndida do oceano. A uma curta distância a pé existem muitos restaurantes e bares, supermercados e locais típicos. A praia nas proximidades é muito bonita. Altamente recomendado.',
    en: 'Luís was very kind. Due to a flight delay, we arrived very late, and he waited for us to give us the keys, also helping us carry our bags to the apartment. He was friendly and we had a very pleasant conversation. The apartment is very nice and well maintained, with an equipped kitchen and everything very clean. The small terrace has a splendid ocean view. Within a short walk there are many restaurants and bars, supermarkets and local spots. The nearby beach is very beautiful. Highly recommended.',
    fr: 'Luís a été très gentil. En raison d\'un retard de vol, nous sommes arrivés très tard et il nous a attendus pour nous remettre les clés, nous aidant aussi à porter nos bagages. Il était sympathique et nous avons eu une conversation très agréable. L\'appartement est très agréable et bien entretenu, avec une cuisine équipée et tout très propre. La petite terrasse offre une vue splendide sur l\'océan. À quelques minutes à pied, de nombreux restaurants, bars et supermarchés. La plage à proximité est très belle. Hautement recommandé.',
    es: 'Luís fue muy amable. Debido a un retraso en el vuelo, llegamos muy tarde y nos esperó para darnos las llaves, ayudándonos también a llevar las maletas. Fue simpático y tuvimos una conversación muy agradable. El apartamento es muy agradable y bien conservado, con cocina equipada y todo muy limpio. La pequeña terraza tiene una vista espléndida del océano. A poca distancia hay muchos restaurantes, bares y supermercados. La playa cercana es muy bonita. Muy recomendado.',
    de: 'Luís war sehr freundlich. Wegen einer Flugverspätung kamen wir sehr spät an, und er wartete auf uns, um uns die Schlüssel zu geben und half uns mit dem Gepäck. Er war sympathisch und wir hatten ein sehr angenehmes Gespräch. Die Wohnung ist sehr schön und gut gepflegt, mit ausgestatteter Küche und alles sehr sauber. Die kleine Terrasse bietet einen herrlichen Meerblick. In kurzer Gehentfernung gibt es viele Restaurants, Bars und Supermärkte. Der nahe Strand ist sehr schön. Sehr empfehlenswert.',
  }),
  defineTestimonial('mar-a-vista-maria', 'mar-a-vista', 'María Inmaculada', 'spain', {
    pt: 'Passámos alguns dias em família e a experiência foi muito positiva. O apartamento tinha tudo o que precisa para uma estadia confortável. Estava muito limpo e bem equipado. A área é muito tranquila, ideal para descansar e relaxar, e em apenas dez minutos chega à praia. Além disso, as vistas são muito agradáveis e dão um valor especial ao alojamento. O Jorge e o Luís foram sempre muito simpáticos e prestativos, facilitando a nossa estadia. É definitivamente um lugar ao qual não nos importaríamos de voltar. Altamente recomendado!',
    en: 'We spent a few days as a family and the experience was very positive. The apartment had everything needed for a comfortable stay. It was very clean and well equipped. The area is very quiet, ideal for resting and relaxing, and the beach is just ten minutes away. The views are very pleasant and add special value to the accommodation. Jorge and Luís were always very friendly and helpful, making our stay easier. Definitely a place we would not mind returning to. Highly recommended!',
    fr: 'Nous avons passé quelques jours en famille et l\'expérience a été très positive. L\'appartement avait tout le nécessaire pour un séjour confortable. Très propre et bien équipé. Le quartier est très calme, idéal pour se reposer, et la plage est à dix minutes. Les vues sont très agréables et apportent une valeur spéciale au logement. Jorge et Luís étaient toujours très sympathiques et serviables. C\'est définitivement un endroit où nous reviendrions. Hautement recommandé !',
    es: 'Pasamos unos días en familia y la experiencia fue muy positiva. El apartamento tenía todo lo necesario para una estancia cómoda. Estaba muy limpio y bien equipado. La zona es muy tranquila, ideal para descansar, y en solo diez minutos se llega a la playa. Las vistas son muy agradables y dan un valor especial al alojamiento. Jorge y Luís fueron siempre muy amables y serviciales. Es definitivamente un lugar al que no nos importaría volver. ¡Muy recomendado!',
    de: 'Wir verbrachten ein paar Tage als Familie und die Erfahrung war sehr positiv. Die Wohnung hatte alles für einen komfortablen Aufenthalt. Sehr sauber und gut ausgestattet. Die Gegend ist sehr ruhig, ideal zum Entspannen, und der Strand ist in nur zehn Minuten erreichbar. Die Aussicht ist sehr angenehm und verleiht der Unterkunft besonderen Wert. Jorge und Luís waren immer sehr freundlich und hilfsbereit. Definitiv ein Ort, an den wir gerne zurückkehren würden. Sehr empfehlenswert!',
  }),
  defineTestimonial('casa-azul-kim', 'casa-azul', 'Kim', 'portugal', {
    pt: 'O Jorge foi incrível e ajudou muito quando não consegui navegar no estacionamento. A localização é excelente, exceto a situação do estacionamento. No entanto, se estiver disposto a pagar um pouco mais para estacionar no parque de estacionamento da praia, vai adorar o lugar. Excelente localização, mas mais importante, excelente anfitrião no check-in!',
    en: 'Jorge was incredible and helped a lot when I couldn\'t navigate the parking. The location is excellent, except for the parking situation. However, if you are willing to pay a little more to park at the beach parking lot, you will love the place. Excellent location, but more importantly, excellent host at check-in!',
    fr: 'Jorge était incroyable et m\'a beaucoup aidée quand je n\'arrivais pas à me repérer pour le parking. L\'emplacement est excellent, sauf pour le stationnement. Cependant, si vous êtes prêt à payer un peu plus pour le parking de la plage, vous adorerez l\'endroit. Excellent emplacement, mais surtout, excellent hôte à l\'arrivée !',
    es: 'Jorge fue increíble y ayudó mucho cuando no pude orientarme con el aparcamiento. La ubicación es excelente, excepto la situación del aparcamiento. Sin embargo, si estás dispuesto a pagar un poco más por aparcar en el parking de la playa, te encantará el lugar. Excelente ubicación, pero lo más importante, excelente anfitrión en el check-in.',
    de: 'Jorge war unglaublich und half mir sehr, als ich mich beim Parken nicht zurechtfinden konnte. Die Lage ist ausgezeichnet, außer beim Parken. Wenn man bereit ist, etwas mehr für den Strandparkplatz zu zahlen, wird man den Ort lieben. Ausgezeichnete Lage, aber vor allem ein ausgezeichneter Gastgeber beim Check-in!',
  }),
  defineTestimonial('casa-da-alegria-pablo', 'casa-da-alegria', 'Pablo', 'portugal', {
    pt: 'Ótimo lugar com uma piscina privada e perto da praia. O anfitrião foi muito simpático e tornou a nossa estadia lá muito agradável.',
    en: 'Great place with a private pool and close to the beach. The host was very friendly and made our stay there very pleasant.',
    fr: 'Super endroit avec une piscine privée et près de la plage. L\'hôte était très sympathique et a rendu notre séjour très agréable.',
    es: 'Gran lugar con piscina privada y cerca de la playa. El anfitrión fue muy amable y hizo nuestra estancia muy agradable.',
    de: 'Toller Ort mit privatem Pool und nahe am Strand. Der Gastgeber war sehr freundlich und machte unseren Aufenthalt sehr angenehm.',
  }),
  defineTestimonial('casa-da-alegria-luis', 'casa-da-alegria', 'Luís', 'portugal', {
    pt: 'Só posso dizer bem. Sempre disponíveis para ajudar no que fosse preciso, antes ou durante a estadia. A casa em cima foi outra boa surpresa. Bastante confortável e perto da lagoa.',
    en: 'I can only say good things. Always available to help with whatever was needed, before or during the stay. The upstairs house was another nice surprise. Very comfortable and near the lagoon.',
    fr: 'Je ne peux que dire du bien. Toujours disponibles pour aider en cas de besoin, avant ou pendant le séjour. La maison à l\'étage était une autre bonne surprise. Très confortable et près de la lagune.',
    es: 'Solo puedo decir cosas buenas. Siempre disponibles para ayudar en lo que fuera necesario, antes o durante la estancia. La casa de arriba fue otra buena sorpresa. Muy cómoda y cerca de la laguna.',
    de: 'Ich kann nur Gutes sagen. Immer verfügbar, um zu helfen — vor oder während des Aufenthalts. Das Haus oben war eine weitere schöne Überraschung. Sehr komfortabel und nahe der Lagune.',
  }),
  defineTestimonial('casa-da-alegria-dorota', 'casa-da-alegria', 'Dorota', 'poland', {
    pt: 'Tivemos uma estadia maravilhosa nesta casa de férias! A casa é espaçosa, perfeita para um grupo maior: quatro quartos confortáveis e três casas de banho proporcionaram-nos total conforto e privacidade. Os interiores estão decorados com bom gosto e a cozinha está bem equipada. O anfitrião merece uma menção especial: foi extremamente prestativo e gentil, respondeu a todas as perguntas rapidamente e as suas dicas sobre a região foram inestimáveis. Recomendamo-lo vivamente a quem procure um alojamento confortável e bem organizado para umas férias tranquilas e inesquecíveis à beira-mar, perto de Lisboa.',
    en: 'We had a wonderful stay at this holiday home! The house is spacious, perfect for a larger group: four comfortable bedrooms and three bathrooms gave us total comfort and privacy. The interiors are tastefully decorated and the kitchen is well equipped. The host deserves special mention: extremely helpful and kind, answered all questions quickly and his tips about the region were invaluable. We highly recommend it to anyone looking for comfortable, well-organized accommodation for a peaceful and unforgettable seaside holiday near Lisbon.',
    fr: 'Nous avons passé un merveilleux séjour dans cette maison de vacances ! La maison est spacieuse, parfaite pour un grand groupe : quatre chambres confortables et trois salles de bain nous ont offert confort et intimité. Les intérieurs sont décorés avec goût et la cuisine est bien équipée. L\'hôte mérite une mention spéciale : extrêmement serviable et gentil, il a répondu rapidement à toutes nos questions et ses conseils sur la région étaient inestimables. Nous le recommandons vivement.',
    es: '¡Tuvimos una estancia maravillosa en esta casa de vacaciones! La casa es espaciosa, perfecta para un grupo grande: cuatro dormitorios cómodos y tres baños nos dieron total confort y privacidad. Los interiores están decorados con buen gusto y la cocina está bien equipada. El anfitrión merece una mención especial: extremadamente servicial y amable, respondió rápidamente a todas las preguntas y sus consejos sobre la región fueron invaluables. Lo recomendamos encarecidamente.',
    de: 'Wir hatten einen wunderbaren Aufenthalt in diesem Ferienhaus! Das Haus ist geräumig, perfekt für eine größere Gruppe: vier komfortable Schlafzimmer und drei Badezimmer boten uns vollen Komfort und Privatsphäre. Die Inneneinrichtung ist geschmackvoll und die Küche gut ausgestattet. Der Gastgeber verdient besondere Erwähnung: äußerst hilfsbereit und freundlich, beantwortete alle Fragen schnell und seine Tipps zur Region waren unschätzbar. Sehr empfehlenswert.',
  }),
  defineTestimonial('casa-luminosa-ana', 'casa-luminosa', 'Ana', 'uk', {
    pt: 'Divertimo-nos imenso em Sesimbra. A DolceStay foi o espaço perfeito para nós. Podíamos ir a qualquer lugar a pé a partir daqui. Ótima padaria e pequeno supermercado com tudo o que era necessário ao virar da esquina. A uma curta distância a pé da praia, do mercado, de restaurantes e de cafés. A casa corresponde à descrição e foi perfeita para as nossas férias. A varanda e as grandes janelas e portas eram adoráveis — um momento tão agradável quando tomámos o nosso café de manhã a olhar para fora. Definitivamente voltaríamos. Os anfitriões foram super simpáticos e prestáveis. A comunicação foi perfeita.',
    en: 'We had a great time in Sesimbra. DolceStay was the perfect place for us. We could walk anywhere from here. Great bakery and small supermarket with all that was needed just around the corner. Short walk to the beach, the market, restaurants, coffee shops. The house matches the description and was perfect for our holiday. The balcony and the big windows and doors were lovely — such a nice moment when we had our coffee in the morning looking outside. We would definitely come back. The hosts were super friendly and helpful. Communication was perfect.',
    fr: 'Nous avons passé un excellent moment à Sesimbra. DolceStay était l\'endroit parfait pour nous. Nous pouvions aller partout à pied. Excellente boulangerie et petite épicerie à deux pas. À quelques minutes à pied de la plage, du marché, des restaurants et cafés. La maison correspond à la description et était parfaite pour nos vacances. Le balcon et les grandes fenêtres étaient adorables. Nous reviendrions sans hésiter. Les hôtes étaient super sympathiques et serviables. Communication parfaite.',
    es: 'Lo pasamos genial en Sesimbra. DolceStay fue el lugar perfecto para nosotros. Podíamos ir a cualquier sitio a pie. Excelente panadería y pequeño supermercado a la vuelta de la esquina. A poca distancia a pie de la playa, el mercado, restaurantes y cafés. La casa coincide con la descripción y fue perfecta para nuestras vacaciones. El balcón y las grandes ventanas eran encantadores. Sin duda volveríamos. Los anfitriones fueron super amables y serviciales. Comunicación perfecta.',
    de: 'Wir hatten eine tolle Zeit in Sesimbra. DolceStay war der perfekte Ort für uns. Von hier aus konnten wir überall zu Fuß hingehen. Tolle Bäckerei und kleiner Supermarkt um die Ecke. Kurzer Fußweg zum Strand, Markt, Restaurants und Cafés. Das Haus entspricht der Beschreibung und war perfekt für unseren Urlaub. Der Balkon und die großen Fenster waren herrlich. Wir würden definitiv wiederkommen. Die Gastgeber waren super freundlich und hilfsbereit. Kommunikation war perfekt.',
  }),
  defineTestimonial('sesimbra-99-rita', 'sesimbra-99', 'Rita', 'portugal', {
    pt: 'Adorei e aconselho a estadia. Os anfitriões são super acessíveis e atenciosos. A casa encontra-se bem equipada e bem localizada. A vista é excelente. Certamente que será uma opção futura. Um grande bem haja a todos os que fazem parte deste projeto.',
    en: 'I loved it and recommend the stay. The hosts are super approachable and attentive. The house is well equipped and well located. The view is excellent. It will certainly be a future option. A big thank you to everyone who is part of this project.',
    fr: 'J\'ai adoré et je recommande le séjour. Les hôtes sont super accessibles et attentionnés. La maison est bien équipée et bien située. La vue est excellente. Ce sera certainement une option future. Un grand merci à tous ceux qui font partie de ce projet.',
    es: 'Me encantó y recomiendo la estancia. Los anfitriones son super accesibles y atentos. La casa está bien equipada y bien ubicada. La vista es excelente. Sin duda será una opción futura. Un gran agradecimiento a todos los que forman parte de este proyecto.',
    de: 'Ich habe es geliebt und empfehle den Aufenthalt. Die Gastgeber sind super zugänglich und aufmerksam. Das Haus ist gut ausgestattet und gut gelegen. Die Aussicht ist ausgezeichnet. Es wird sicher eine Option für die Zukunft sein. Ein großes Dankeschön an alle, die Teil dieses Projekts sind.',
  }),
  defineTestimonial('castle-apartment-rosa', 'castle-apartment', 'Rosa', 'canada', {
    pt: 'Tivemos uma excelente estadia! A propriedade era bonita, excecionalmente limpa e tinha tudo o que precisávamos para uma visita confortável. As camas eram muito confortáveis, o que nos ajudou a ter uma ótima noite de sono. O Luís recebeu-nos quando chegámos e foi incrivelmente acolhedor, simpático e prestável. O Luís, o Jorge e o Chris responderam rapidamente às mensagens. A localização também era excelente: a praia ficava a apenas 2,5 km de distância e era fácil de chegar lá, e o castelo ficava a menos de 20 minutos a pé. Recomendamos vivamente a qualquer pessoa que visite a região!',
    en: 'We had an excellent stay! The property was beautiful, exceptionally clean and had everything we needed for a comfortable visit. The beds were very comfortable, which helped us get a great night\'s sleep. Luís welcomed us when we arrived and was incredibly welcoming, friendly and helpful. Luís, Jorge and Chris responded quickly to messages. The location was also excellent: the beach was just 2.5 km away and easy to reach, and the castle was less than a 20-minute walk. We highly recommend it to anyone visiting the region!',
    fr: 'Nous avons passé un excellent séjour ! La propriété était belle, exceptionnellement propre et avait tout ce dont nous avions besoin. Les lits étaient très confortables. Luís nous a accueillis à notre arrivée et a été incroyablement accueillant, sympathique et serviable. Luís, Jorge et Chris ont répondu rapidement aux messages. L\'emplacement était également excellent : la plage à seulement 2,5 km et le château à moins de 20 minutes à pied. Nous recommandons vivement à tous ceux qui visitent la région !',
    es: '¡Tuvimos una excelente estancia! La propiedad era bonita, excepcionalmente limpia y tenía todo lo que necesitábamos. Las camas eran muy cómodas. Luís nos recibió a nuestra llegada y fue increíblemente acogedor, amable y servicial. Luís, Jorge y Chris respondieron rápidamente a los mensajes. La ubicación también era excelente: la playa a solo 2,5 km y el castillo a menos de 20 minutos a pie. ¡Lo recomendamos encarecidamente a quien visite la región!',
    de: 'Wir hatten einen ausgezeichneten Aufenthalt! Die Unterkunft war schön, außergewöhnlich sauber und hatte alles, was wir brauchten. Die Betten waren sehr bequem. Luís begrüßte uns bei der Ankunft und war unglaublich einladend, freundlich und hilfsbereit. Luís, Jorge und Chris antworteten schnell auf Nachrichten. Die Lage war auch ausgezeichnet: der Strand nur 2,5 km entfernt und die Burg weniger als 20 Minuten zu Fuß. Wir empfehlen es jedem, der die Region besucht!',
  }),
  defineTestimonial('dolceplace-claudia', 'dolceplace', 'Cláudia', 'portugal', {
    pt: 'Tivemos uma estadia ótima neste apartamento. É muito confortável, acolhedor e está situado num bairro calmo, perfeito para descansar e desfrutar das férias. As camas são muito confortáveis. A praia fica a apenas 10 minutos, o que é uma grande vantagem. Um destaque especial vai para os proprietários, que foram excecionais desde o primeiro momento. Sempre disponíveis, atentos e preocupados em garantir que não nos faltava nada. Recomendamos este alojamento sem hesitar e esperamos voltar no futuro!',
    en: 'We had a great stay in this apartment. It is very comfortable, welcoming and located in a quiet neighbourhood, perfect for resting and enjoying the holidays. The beds are very comfortable. The beach is just 10 minutes away, which is a big advantage. Special mention goes to the owners, who were exceptional from the very first moment. Always available, attentive and concerned to ensure we lacked nothing. We recommend this accommodation without hesitation and hope to return in the future!',
    fr: 'Nous avons passé un excellent séjour dans cet appartement. Très confortable, accueillant et situé dans un quartier calme, parfait pour se reposer. Les lits sont très confortables. La plage est à seulement 10 minutes, un grand avantage. Mention spéciale aux propriétaires, exceptionnels dès le premier moment. Toujours disponibles et attentifs. Nous recommandons cet hébergement sans hésiter et espérons revenir !',
    es: 'Tuvimos una estancia estupenda en este apartamento. Es muy cómodo, acogedor y está en un barrio tranquilo, perfecto para descansar. Las camas son muy cómodas. La playa está a solo 10 minutos, una gran ventaja. Mención especial a los propietarios, excepcionales desde el primer momento. Siempre disponibles y atentos. Recomendamos este alojamiento sin dudarlo y esperamos volver.',
    de: 'Wir hatten einen großartigen Aufenthalt in dieser Wohnung. Sehr komfortabel, einladend und in einer ruhigen Nachbarschaft — perfekt zum Entspannen. Die Betten sind sehr bequem. Der Strand ist nur 10 Minuten entfernt, ein großer Vorteil. Besondere Erwähnung an die Eigentümer, die vom ersten Moment an außergewöhnlich waren. Immer verfügbar und aufmerksam. Wir empfehlen diese Unterkunft ohne zu zögern und hoffen, zurückzukehren!',
  }),
  defineTestimonial('dolceplace-sonia', 'dolceplace', 'Sonia', 'uk', {
    pt: 'Adorámos a nossa estadia, apartamento muito agradável com todos os itens essenciais, quartos espaçosos e ambiente confortável e tranquilo. A uma curta caminhada da praia. E o Jorge foi muito recetivo e sentimo-nos à vontade para o contactar.',
    en: 'We loved our stay — very pleasant apartment with all the essential items, spacious bedrooms and a comfortable, quiet atmosphere. A short walk from the beach. And Jorge was very receptive and we felt comfortable contacting him.',
    fr: 'Nous avons adoré notre séjour — appartement très agréable avec tous les essentiels, chambres spacieuses et ambiance confortable et tranquille. À quelques minutes à pied de la plage. Jorge a été très réactif et nous nous sommes sentis à l\'aise pour le contacter.',
    es: 'Adoramos nuestra estancia — apartamento muy agradable con todos los elementos esenciales, habitaciones espaciosas y ambiente cómodo y tranquilo. A poca distancia a pie de la playa. Jorge fue muy receptivo y nos sentimos cómodos contactándole.',
    de: 'Wir liebten unseren Aufenthalt — sehr angenehme Wohnung mit allen Essentials, geräumige Schlafzimmer und eine komfortable, ruhige Atmosphäre. Kurzer Fußweg zum Strand. Jorge war sehr aufgeschlossen und wir fühlten uns wohl, ihn zu kontaktieren.',
  }),
  defineTestimonial('quinta-das-figueiras-tiago', 'quinta-das-figueiras', 'Tiago', 'portugal', {
    pt: 'O espaço é agradável. Ideal para descansar e perto das praias.',
    en: 'The space is pleasant. Ideal for resting and close to the beaches.',
    fr: 'L\'espace est agréable. Idéal pour se reposer et près des plages.',
    es: 'El espacio es agradable. Ideal para descansar y cerca de las playas.',
    de: 'Der Raum ist angenehm. Ideal zum Entspannen und nahe den Stränden.',
  }),
  defineTestimonial('seaflower-house-marcus', 'seaflower-house', 'Marcus', 'portugal', {
    pt: 'Comunicação muito boa, o Jorge foi muito prestativo e muito atencioso. Eu e a minha família adorámos o espaço e a localização é excelente. Com certeza voltaremos.',
    en: 'Very good communication, Jorge was very helpful and very attentive. My family and I loved the space and the location is excellent. We will definitely return.',
    fr: 'Très bonne communication, Jorge a été très serviable et très attentionné. Ma famille et moi avons adoré l\'espace et l\'emplacement est excellent. Nous reviendrons certainement.',
    es: 'Muy buena comunicación, Jorge fue muy servicial y muy atento. A mi familia y a mí nos encantó el espacio y la ubicación es excelente. Sin duda volveremos.',
    de: 'Sehr gute Kommunikation, Jorge war sehr hilfsbereit und aufmerksam. Meine Familie und ich liebten den Raum und die Lage ist ausgezeichnet. Wir werden sicher wiederkommen.',
  }),
  defineTestimonial('seaflower-house-prado', 'seaflower-house', 'Prado', 'spain', {
    pt: 'Está tudo muito bom. O apartamento é muito espaçoso, luminoso, bem equipado e está tudo muito limpo. Fica numa zona de fácil acesso e tranquila. O anfitrião recebeu-nos à chegada, informou-nos de tudo o que era necessário e comunicou sempre connosco. Muito simpático. Uma estadia muito agradável. Voltaremos.',
    en: 'Everything is very good. The apartment is very spacious, bright, well equipped and everything is very clean. It is in an area with easy access and is quiet. The host met us on arrival, informed us of everything necessary and always communicated with us. Very friendly. A very pleasant stay. We will return.',
    fr: 'Tout est très bien. L\'appartement est très spacieux, lumineux, bien équipé et tout est très propre. Il se trouve dans une zone facile d\'accès et tranquille. L\'hôte nous a accueillis à l\'arrivée, nous a informés de tout le nécessaire et a toujours communiqué avec nous. Très sympathique. Un séjour très agréable. Nous reviendrons.',
    es: 'Está todo muy bien. El apartamento es muy espacioso, luminoso, bien equipado y todo está muy limpio. Está en una zona de fácil acceso y tranquila. El anfitrión nos recibió a la llegada, nos informó de todo lo necesario y siempre se comunicó con nosotros. Muy amable. Una estancia muy agradable. Volveremos.',
    de: 'Alles ist sehr gut. Die Wohnung ist sehr geräumig, hell, gut ausgestattet und alles ist sehr sauber. Sie liegt in einer gut erreichbaren und ruhigen Gegend. Der Gastgeber empfing uns bei der Ankunft, informierte uns über alles Notwendige und kommunizierte stets mit uns. Sehr freundlich. Ein sehr angenehmer Aufenthalt. Wir kommen wieder.',
  }),
  defineTestimonial('vista-azul-chris', 'vista-azul', 'Chris', 'germany', {
    pt: 'Super satisfeitos com a nossa estadia. O Jorge tratou de tudo, recebeu-nos muito bem e mostrou-nos tudo. Teremos todo o prazer em voltar.',
    en: 'Super satisfied with our stay. Jorge took care of everything, welcomed us very well and showed us everything. We will be very happy to return.',
    fr: 'Super satisfaits de notre séjour. Jorge s\'est occupé de tout, nous a très bien accueillis et nous a tout montré. Nous serons ravis de revenir.',
    es: 'Super satisfechos con nuestra estancia. Jorge se encargó de todo, nos recibió muy bien y nos mostró todo. Estaremos encantados de volver.',
    de: 'Super zufrieden mit unserem Aufenthalt. Jorge hat sich um alles gekümmert, uns sehr herzlich empfangen und uns alles gezeigt. Wir kommen gerne wieder.',
  }),
  defineTestimonial('villa-pinheirinhos-eva', 'villa-pinheirinhos', 'Eva', 'germany', {
    pt: 'É uma casa muito bem renovada e decorada. Adorei o interior e o cuidado do gerente da casa.',
    en: 'It is a very well renovated and decorated house. I loved the interior and the care of the house manager.',
    fr: 'C\'est une maison très bien rénovée et décorée. J\'ai adoré l\'intérieur et l\'attention du gestionnaire de la maison.',
    es: 'Es una casa muy bien renovada y decorada. Me encantó el interior y el cuidado del administrador de la casa.',
    de: 'Es ist ein sehr gut renoviertes und dekoriertes Haus. Ich liebte das Interieur und die Fürsorge des Hausmanagers.',
  }),
  defineTestimonial('villa-manuelina-greg', 'villa-manuelina', 'Greg', 'netherlands', {
    pt: 'Três gerações da nossa família tiveram uma semana fabulosamente agradável nesta villa espaçosa. As crianças apreciaram a Casa da Wendy e os brinquedos, enquanto os adultos mais jovens apreciaram o ginásio e as salas de jogos. Todos gostaram da piscina e da sala de piscina separada com os seus sofás confortáveis. Comer fora é fácil, se desejar, pois Sesimbra fica a uma curta viagem de táxi e tem uma ótima variedade de restaurantes. A praia de Sesimbra é encantadora e limpa e foi um verdadeiro sucesso com as crianças.',
    en: 'Three generations of our family had a fabulously pleasant week in this spacious villa. The children enjoyed the Wendy house and toys, while the younger adults enjoyed the gym and game rooms. Everyone loved the pool and the separate pool room with its comfortable sofas. Eating out is easy if you wish, as Sesimbra is a short taxi ride away and has a great variety of restaurants. Sesimbra beach is charming and clean and was a real hit with the children.',
    fr: 'Trois générations de notre famille ont passé une semaine fabuleusement agréable dans cette villa spacieuse. Les enfants ont adoré la maison Wendy et les jouets, tandis que les jeunes adultes ont apprécié la salle de sport et les salles de jeux. Tout le monde a adoré la piscine et la salle de piscine séparée avec ses canapés confortables. Sesimbra est à un court trajet en taxi avec une grande variété de restaurants. La plage de Sesimbra est charmante et propre — un vrai succès auprès des enfants.',
    es: 'Tres generaciones de nuestra familia pasaron una semana fabulosamente agradable en esta villa espaciosa. Los niños disfrutaron de la casita Wendy y los juguetes, mientras que los adultos jóvenes disfrutaron del gimnasio y las salas de juegos. A todos les encantó la piscina y la sala de piscina separada con sus cómodos sofás. Sesimbra está a un corto trayecto en taxi y tiene una gran variedad de restaurantes. La playa de Sesimbra es encantadora y limpia — un éxito total con los niños.',
    de: 'Drei Generationen unserer Familie verbrachten eine fabulose Woche in dieser geräumigen Villa. Die Kinder genossen das Wendy-Haus und das Spielzeug, während die jüngeren Erwachsenen das Fitnessstudio und die Spielräume schätzten. Alle liebten den Pool und den separaten Poolraum mit seinen bequemen Sofas. Sesimbra ist eine kurze Taxifahrt entfernt und bietet eine große Restaurantvielfalt. Der Strand von Sesimbra ist charmant und sauber — ein echter Hit bei den Kindern.',
  }),
  defineTestimonial('villa-manuelina-ben', 'villa-manuelina', 'Ben', 'uk', {
    pt: 'Ótima villa. Com a piscina e todos os jogos, as crianças estiveram entretidas o tempo todo. Os Ubers chegam em poucos minutos, o que considerámos uma alternativa mais barata e fácil do que alugar um carro para chegar à praia. Vista agradável do terraço também. Também tivemos uma boa receção presencial do Luís.',
    en: 'Great villa. With the pool and all the games, the children were entertained all the time. Ubers arrive in a few minutes, which we considered a cheaper and easier alternative than renting a car to get to the beach. Nice view from the terrace too. We also had a good in-person welcome from Luís.',
    fr: 'Superbe villa. Avec la piscine et tous les jeux, les enfants étaient occupés tout le temps. Les Ubers arrivent en quelques minutes, ce que nous avons considéré comme une alternative moins chère et plus facile que la location d\'une voiture pour aller à la plage. Belle vue depuis la terrasse aussi. Nous avons aussi eu un excellent accueil en personne de Luís.',
    es: 'Gran villa. Con la piscina y todos los juegos, los niños estuvieron entretenidos todo el tiempo. Los Ubers llegan en pocos minutos, lo que consideramos una alternativa más barata y fácil que alquilar un coche para ir a la playa. Bonita vista desde la terraza también. También tuvimos una buena recepción presencial de Luís.',
    de: 'Tolle Villa. Mit dem Pool und all den Spielen waren die Kinder die ganze Zeit beschäftigt. Ubers kommen in wenigen Minuten — für uns eine günstigere und einfachere Alternative als ein Mietwagen zum Strand. Schöne Aussicht von der Terrasse. Wir hatten auch einen guten persönlichen Empfang von Luís.',
  }),
];

export const testimonialPropertyKeys = testimonialDefinitions.map((item) => item.propertyKey);

export function getTestimonialItems(language: Language): TestimonialItem[] {
  return testimonialDefinitions.map((item) => ({
    author: item.author,
    location: country[item.country][language],
    type: 'guest' as const,
    rating: 5 as const,
    text: item.text[language],
  }));
}
